/* Builds every lookup table from cube.h and writes tables.c (for C) and
 * tables.s (for the RV32I program).
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "cube.h"

static uint16_t pt[3][NPERM], ot[3][NORI];
static uint8_t pd[NPERM], pos[NPERM], opd[NORI * OSTRIDE];

static void build_transitions(void)
{
    state_t s;
    for (uint32_t r = 0; r < NPERM; ++r) {
        unrank(r, 0, &s);
        pos[r] = (uint8_t) pos_code(&s);
        for (int f = 0; f < 3; ++f) {
            state_t n = quarter_turn(s, f);
            pt[f][r] = (uint16_t) rank_p(&n);
        }
    }
    for (uint32_t r = 0; r < NORI; ++r) {
        unrank(0, r, &s);
        for (int f = 0; f < 3; ++f) {
            state_t n = quarter_turn(s, f);
            ot[f][r] = (uint16_t) rank_o(&n);
        }
    }
}

/* BFS over permutations alone. */
static void build_pd(void)
{
    static uint16_t q[NPERM];
    uint32_t head = 0, tail = 1;
    memset(pd, 0xFF, sizeof pd);
    pd[0] = 0;
    q[0] = 0;
    while (head < tail) {
        uint16_t x = q[head++];
        for (int f = 0; f < 3; ++f)
            for (uint16_t y = pt[f][x]; y != x; y = pt[f][y])
                if (pd[y] == 0xFF) {
                    pd[y] = (uint8_t) (pd[x] + 1);
                    q[tail++] = y;
                }
    }
}

/* BFS over (orientation, POS).  The queue holds one representative (p, o)
 * per abstract state; any representative has the same abstract successors,
 * because the projection commutes with moves.  Padding columns 42..63 stay
 * 0xFF.
 */
static void build_opd(void)
{
    static uint16_t qp[NORI * NPOS], qo[NORI * NPOS];
    uint32_t head = 0, tail = 1;
    memset(opd, 0xFF, sizeof opd);
    opd[((uint32_t) 0 << 6) | pos[0]] = 0;
    qp[0] = qo[0] = 0;
    while (head < tail) {
        uint16_t p = qp[head], o = qo[head++];
        uint8_t d = opd[((uint32_t) o << 6) | pos[p]];
        for (int f = 0; f < 3; ++f) {
            uint16_t np = p, no = o;
            for (int t = 0; t < 3; ++t) {
                np = pt[f][np];
                no = ot[f][no];
                uint32_t i = ((uint32_t) no << 6) | pos[np];
                if (opd[i] == 0xFF) {
                    opd[i] = (uint8_t) (d + 1);
                    qp[tail] = np;
                    qo[tail++] = no;
                }
            }
        }
    }
    if (tail != NORI * NPOS) {
        fprintf(stderr, "OPD BFS reached %u of %u\n", tail, NORI * NPOS);
        exit(1);
    }
}

/* rows > 1 emits a two-dimensional initializer, one brace pair per row. */
static void emit_c(FILE *f, const char *decl, const void *data, size_t n,
                   int wide, size_t rows)
{
    size_t cols = n / rows;
    fprintf(f, "%s = {", decl);
    for (size_t i = 0; i < n; ++i) {
        unsigned v = wide ? ((const uint16_t *) data)[i]
                          : ((const uint8_t *) data)[i];
        size_t c = i % cols;
        if (rows > 1 && c == 0)
            fprintf(f, "%s\n  {", i ? "}," : "");
        fprintf(f, "%s%u", c == 0 ? "\n    " : c % 16 ? "," : ",\n    ", v);
    }
    fprintf(f, "%s\n};\n\n", rows > 1 ? "}" : "");
}

static void emit_s(FILE *f, const char *label, const void *data, size_t n,
                   int wide)
{
    fprintf(f, "%s:\n", label);
    for (size_t i = 0; i < n; ++i) {
        unsigned v = wide ? ((const uint16_t *) data)[i]
                          : ((const uint8_t *) data)[i];
        fprintf(f, "%s%u", i % 16 ? "," : wide ? "\n    .half " : "\n    .byte ",
                v);
    }
    fprintf(f, "\n");
}

int main(void)
{
    build_transitions();
    build_pd();
    build_opd();

    FILE *c = fopen("tables.c", "w"), *s = fopen("tables.s", "w");
    if (!c || !s) {
        perror("tables");
        return 1;
    }
    fprintf(c, "/* Generated by gen_tables.c; do not edit. */\n"
               "#include \"tables.h\"\n\n");
    emit_c(c, "const uint16_t PT[3][NPERM]", pt, 3 * NPERM, 1, 3);
    emit_c(c, "const uint16_t OT[3][NORI]", ot, 3 * NORI, 1, 3);
    emit_c(c, "const uint8_t PD[NPERM]", pd, NPERM, 0, 1);
    emit_c(c, "const uint8_t POS[NPERM]", pos, NPERM, 0, 1);
    emit_c(c, "const uint8_t OPD[NORI * OSTRIDE]", opd, NORI * OSTRIDE, 0, 1);

    /* 16-bit tables first, so they stay 2-byte aligned. */
    fprintf(s, "# Generated by gen_tables.c; do not edit.\n"
               "# PT[3][5040] u16, OT[3][729] u16, PD[5040] u8, POS[5040] u8,\n"
               "# OPD[729*64] u8 indexed (o << 6) | POS[p].\n"
               ".data\n");
    emit_s(s, "PT", pt, 3 * NPERM, 1);
    emit_s(s, "OT", ot, 3 * NORI, 1);
    emit_s(s, "PD", pd, NPERM, 0);
    emit_s(s, "POS", pos, NPERM, 0);
    emit_s(s, "OPD", opd, NORI * OSTRIDE, 0);

    if (fclose(c) || fclose(s)) {
        perror("tables");
        return 1;
    }
    printf("tables: %zu bytes\n", sizeof pt + sizeof ot + sizeof pd +
                                       sizeof pos + sizeof opd);
    return 0;
}
